### ISSUE TITLE
Is there an introduction for this repo?

### ISSUE THREAD

**Issue by zzxwill** [devsapp/start-component#1]
@hanxie-crypto Is there an introduction for this repo?

**Comment by anycodes** [comment]
This repo is a 'how init serverless devs component' example.
if you want to get it in your serverless devs cli, you could run `s init` and select `component`, you also could get more documents, like: 
https://github.com/devsapp/start-component/blob/master/src/readme.md
https://github.com/Serverless-Devs/docs/blob/master/zh/dev.md
